# Generated by Django 5.1.4 on 2024-12-25 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='In format: CountryCode PhoneNumber (+977 9812345678)', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+977|\\+91)[\\s_]?(\\d{10})$')], verbose_name='Contact Number'),
        ),
    ]
