# Generated by Django 5.1.4 on 2024-12-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
